export const env = {
  SHOPIFY_STORE_URL: process.env.SHOPIFY_STORE_URL || "",
  SHOPIFY_ACCESS_TOKEN: process.env.SHOPIFY_ACCESS_TOKEN || "",
  SHOPIFY_WEBHOOK_SECRET: process.env.SHOPIFY_WEBHOOK_SECRET || "",
  DATABASE_HOST: process.env.DATABASE_HOST || "localhost",
  DATABASE_PORT: process.env.DATABASE_PORT || "5432",
  DATABASE_NAME: process.env.DATABASE_NAME || "abandoned_carts",
  DATABASE_USER: process.env.DATABASE_USER || "",
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD || "",
  SMTP_HOST: process.env.SMTP_HOST || "",
  SMTP_PORT: process.env.SMTP_PORT || "587",
  SMTP_USER: process.env.SMTP_USER || "",
  SMTP_PASSWORD: process.env.SMTP_PASSWORD || "",
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || "",
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || "",
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER || "",
  WHATSAPP_API_TOKEN: process.env.WHATSAPP_API_TOKEN || "",
  WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID || "",
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  JWT_SECRET: process.env.JWT_SECRET || "your-jwt-secret",
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || "your-encryption-key",
  ENABLE_REAL_TIME_SYNC: process.env.ENABLE_REAL_TIME_SYNC === "true",
  ENABLE_AI_INSIGHTS: process.env.ENABLE_AI_INSIGHTS === "true",
  ENABLE_BULK_ACTIONS: process.env.ENABLE_BULK_ACTIONS === "true",
  ENABLE_MOCK_DATA: process.env.ENABLE_MOCK_DATA !== "false",
  DEBUG: process.env.DEBUG === "true",
}
